#
# Blog Settings
#
author: malekbenz
title: Malekbenz Blog
subtitle: I'm FullStack Developer
description: Learn how to program with Dotnet, Javascript, C#, ASP.NET , NodeJS, SQL Server, HTML5 & CSS
gravatar_url: http://2.gravatar.com/avatar/8b40bf825a021162659ab478804bff5b"
keywords: Dotnet, Javascript, C#, ASP.NET , NodeJS, SQL Server, HTML5, CSS, malekbenz, gulp, Angularjs 
url: https://malekbenz.com
domain: malekbenz.com
image: /img/siteimage.png
twitter_username: malekbenzemam

# Github repositoriesname: Malekbenz, weblog
#
# Github repositories
github_user: Malekbenz
github_repo_url: https://github.com/malekbenz

# Jekyll Settings
#
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

paginate_path: "page/:num"
category_dir: categories
# Disqus Comments
disqus_short_name: blog-malekbenz-com
disqus_show_comment_count: true

#
gems: [jekyll-paginate]
paginate: 1
exclude: ["README.md"]

