#
# Blog Settings
#
author: Malekbenz
description: I'm FullStack Developer
url: http://Malekbenz.com
title: Malekbenz Blog
subtitle: ...and you like it
gravatar_url: http://2.gravatar.com/avatar/8b40bf825a021162659ab478804bff5b"

# Github repositoriesname: Malekbenz, weblog
#
# Github repositories
github_user: Malekbenz
github_repo_url: https://github.com/malekbenz

# Jekyll Settings
#
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

paginate_path: "page/:num"
category_dir: categories

paginate: 5
exclude: ["README.md"]

